class Locators:
    ENTER_BUTTON_MAIN_PAGE = ".//button[text()='Войти в аккаунт']"   # Кнопка "Войти в аккаунт" на главной странице (XPATH)
    ENTER_BUTTON_PERSONAL_ACCOUNT = "html/body/div/div/main/div/form/button"   # Кнопка "Войти" в форме авторизации (XPATH)
    ENTER_BUTTON_REGISTRATION_FORM = ".//a[@class='Auth_link__1fOlj' and @href='/login']"   # Кнопка "Войти" в форме регистрации (XPATH)
    ENTER_BUTTON_PASSWORD_RECOVERY_FORM = ".//a[@class='Auth_link__1fOlj' and @href='/login']"   # Кнопка "Войти" в форме восстановления пароля (XPATH)
    PERSONAL_ACCOUNT_BUTTON = "html/body/div/div/header/nav/a/p"   # Кнопка "Личный кабинет" (XPATH)
    EXIT_BUTTON_PERSONAL_ACCOUNT = "Account_button__14Yp3"   # Кнопка "Выход" из личного кабинета (CLASS_NAME)
    RECOVERY_PASSWORD_BUTTON = ".//a[@class='Auth_link__1fOlj' and @href='/forgot-password']"   # Кнопка "Восстановить пароль" (XPATH)
    CONSTRUCTOR_BUTTON = ".//p[contains(., 'Конструктор')]"   # Кнопка "Конструктор" бургеров (XPATH)
    LOGO_BUTTON = ".AppHeader_header__logo__2D0X2"   # Кнопка-логотип "Stellar burgers" на главной странице (CSS)
    BUNS_BUTTON = ".//span[text()='Булки']"   # Кнопка переключения "Булки" в конструкторе (XPATH)
    SAUCES_BUTTON = ".//span[text()='Соусы']"   # Кнопка переключения "Соусы" в конструкторе (XPATH)
    FILLINGS_BUTTON = ".//span[text()='Начинки']"   # Кнопка переключения "Начинки" в конструкторе (XPATH)
    CONSTRUCTOR_SELECTED_SECTION = ".//div[contains(@class, 'tab_tab_type_current__2BEPc')]"   # Локатор выбранного раздела в конструкторе (XPATH)
    EMAIL_INPUT = ".//fieldset[1]/div/div/input"   # Поле ввода email (XPATH)
    PASSWORD_INPUT = ".//fieldset[2]/div/div/input"   # Поле ввода пароля (XPATH)
    REGISTER_BUTTON_PERSONAL_ACCOUNT_PAGE = ".//a[contains(@class, 'Auth_link__') and @href='/register']"   # Кнопка "Зарегистрироваться" на странице входа в личный кабинет (XPATH)
    REGISTER_BUTTON_REGISTER_PAGE = ".//button[text()='Зарегистрироваться']"   # Кнопка "Зарегистрироваться" на странице регистрации (XPATH)
    NAME_INPUT_REGISTRATION = ".//fieldset[1]/div/div/input"   # Поле ввода имени при регистрации (XPATH)
    EMAIL_INPUT_REGISTRATION = ".//fieldset[2]/div/div/input"   # Поле ввода email при регистрации (XPATH)
    PASSWORD_INPUT_REGISTRATION = ".//fieldset[3]/div/div/input"   # Поле ввода пароля при регистрации (XPATH)
    ERROR_MESSAGE = "html/body/div/div/main/div/form/fieldset[3]/div/p"   # Сообщение об ошибке (XPATH)


